# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 658018ce84d01e7d044b09af73312bc2e3ad3b19562a4a97f42f6b732ea5cfd9d5818ac1bf3c1b0921a34f3599ba68f357de2bf6a115df09c2a10581e7173b88

test:
  secret_key_base: 23e6e9dec943c33d72e5467c14cebb0f621a452adcb957d88286613f95a87e340a347aeaf0a8d850eb386d628497ec590b322b9587324e99185147d51ba3e14f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
